version: '3.5'

services:
  postgres:
    container_name: game_db
    image: postgres:15.4-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: game
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"